let descriptions = [
    "delightful",
    "delectable",
    "luscious",
    "pleasant-tasting",
    "scrumptious",
    "toothsome",
    "yummy",
    "delicious",
    "hot",
    "blue",
    "gamey",
    "gamy",
    "juicy",
    "naughty",
    "racy",
    "risque",
    "spicy",
    "mouthwatering",
    "appetizing",
    "succulent",
    "rich",
    "savory",
    "piquant",
    "finger-licking good",
    "ambrosial",
    "delish",
    "nummy",
    "nectareous",
    "exquisite",
    "lovely",
    "glorious",
    "heavenly",
    "divine",
    "flavorful",
    "flavorsome",
    "pleasing"
]

module.exports = descriptions;